#+TITLE: CIViCL
#+AUTHOR: Naomi 
* Description
  CIViCL (/pronounced like the first part of civ/ilization with the last part of ice/icl/) is an implementation of the strategy game Civ in common lisp. This system provides the logic of the game itself alongside a client/server architecture. Clients are responsible for any graphical representations, with one exception: A webserver would be a useful interface, and using some sort of image drawing program we could generate graphical representations each turn in the form of a PNG, and send that to the appropriate player. 
* Systems and Subsystems
** CIV
   The main system is just called ~civ~, and is the only thing one should be interacting with. It will provide an interface to all subsystems. 
** TILE
   The tile subsystem organizes our representation of the map. It is depended upon by most other systems, either explicitly or via another subsystem. 
** GAME
   The game subsystem organizes the representation of games, each with their own thread pool and state. This system depends on the subsystems tile, player, and server.
